-- Postgres schema for Product Manager
-- Compatible con Neon (Postgres). Usa nombres en snake_case.

CREATE TABLE IF NOT EXISTS categories (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(120) NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_categories_name ON categories(name);

CREATE TABLE IF NOT EXISTS products (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(160) NOT NULL,
  description  VARCHAR(2000),
  price        NUMERIC(12,2) NOT NULL,
  stock        INTEGER NOT NULL,
  image_url    VARCHAR(1000),
  active       BOOLEAN NOT NULL DEFAULT TRUE,
  category_id  INTEGER NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS ix_products_created_at ON products(created_at);

CREATE TABLE IF NOT EXISTS receipts (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_number VARCHAR(40) NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  total_amount   NUMERIC(12,2) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_receipts_receipt_number ON receipts(receipt_number);
CREATE INDEX IF NOT EXISTS ix_receipts_created_at ON receipts(created_at);

CREATE TABLE IF NOT EXISTS receipt_items (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id  INTEGER NOT NULL REFERENCES receipts(id) ON DELETE CASCADE,
  product_id  INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity    INTEGER NOT NULL,
  unit_price  NUMERIC(12,2) NOT NULL,
  line_total  NUMERIC(12,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_receipt_items_receipt_id ON receipt_items(receipt_id);
CREATE INDEX IF NOT EXISTS ix_receipt_items_product_id ON receipt_items(product_id);

